#------------------------------------------------------------------------------

SOURCE=main.cc Hash.cc Tab_hash.cc Bloom_K.cc
MYPROGRAM=practicaAlg

CC=g++

#------------------------------------------------------------------------------



all: $(MYPROGRAM)



$(MYPROGRAM): $(SOURCE)

	$(CC) $(SOURCE) -o$(MYPROGRAM)

clean:

	rm -f $(MYPROGRAM)
